TARGET = attention_final_v2
compile:
# 	/cluster/home/guoym/xuantie-gnu-toolchain/opt/riscv/bin/riscv64-unknown-elf-gcc -march=rv64gc_zfh_xtheadmatrix -g test.c -o test.elf -O2 -lm -static
# 	/cluster/home/guoym/xuantie-gnu-toolchain/opt/riscv/bin/riscv64-unknown-elf-gcc -march=rv64gc_zfh_xtheadmatrix -g matmul_v2.c -o matmul_v2.elf -O2 -lm -static
# 	/cluster/home/guoym/xuantie-gnu-toolchain/opt/riscv/bin/riscv64-unknown-elf-gcc -march=rv64gc_zfh_xtheadmatrix -g test1.c -o test1.elf -O2 -lm -static
# 	/cluster/home/guoym/xuantie-gnu-toolchain/opt/riscv/bin/riscv64-unknown-elf-gcc -march=rv64gc_zfh_xtheadmatrix -g test2.c -o test2.elf -O2 -lm -static
# 	/cluster/home/guoym/xuantie-gnu-toolchain/opt/riscv/bin/riscv64-unknown-elf-gcc -march=rv64gc_zfh_xtheadmatrix -g test3.c -o test3.elf -O2 -lm -static
# 	/cluster/home/guoym/xuantie-gnu-toolchain/opt/riscv/bin/riscv64-unknown-elf-gcc -march=rv64gc_zfh_xtheadmatrix -g instruction_test.c -o instruction_test.elf -O2 -lm -static
# 	/cluster/home/guoym/xuantie-gnu-toolchain/opt/riscv/bin/riscv64-unknown-elf-gcc -march=rv64gc_zfh_xtheadmatrix -g matmul_u.c -o matmul_u.elf -O2 -lm -static
# 	/cluster/home/guoym/xuantie-gnu-toolchain/opt/riscv/bin/riscv64-unknown-elf-gcc -march=rv64gc_zfh_xtheadmatrix -g matmul_v2_3.c -o matmul_v2_3.elf -O3 -lm -static
# 	/cluster/home/guoym/xuantie-gnu-toolchain/opt/riscv/bin/riscv64-unknown-elf-gcc -march=rv64gc_zfh_xtheadmatrix -g matmul_redc.c -o matmul_redc.elf -O2 -lm -static
# 	/cluster/home/guoym/xuantie-gnu-toolchain/opt/riscv/bin/riscv64-unknown-elf-gcc -march=rv64gc_zfh_xtheadmatrix -g attention_v2.c -o attention_v2.elf -O2 -lm -static
	/cluster/home/guoym/xuantie-gnu-toolchain/opt/riscv/bin/riscv64-unknown-elf-gcc -march=rv64gc_zfh_xtheadmatrix -g $(TARGET).c -o $(TARGET).elf -O2 -lm -static
# 	/cluster/home/guoym/xuantie-gnu-toolchain/opt/riscv/bin/riscv64-unknown-elf-gcc -march=rv64gc_zfh_xtheadmatrix -g loadt_test.c -o loadt_test.elf -O2 -lm -static
# 	/cluster/home/guoym/xuantie-gnu-toolchain/opt/riscv/bin/riscv64-unknown-elf-gcc -march=rv64gc_zfh_xtheadmatrix -g mat_lut.c -o mat_lut.elf -O2 -lm -static
# 	/cluster/home/guoym/xuantie-gnu-toolchain/opt/riscv/bin/riscv64-unknown-elf-gcc -march=rv64gc_zfh_xtheadmatrix -g softmax_v2_1.c -o softmax_v2_1.elf -O2 -lm -static
# 	/cluster/home/guoym/xuantie-gnu-toolchain/opt/riscv/bin/riscv64-unknown-elf-gcc -march=rv64gc_zfh_xtheadmatrix -g attention.c -o attention.elf -O2 -lm -static
# 	/cluster/home/guoym/xuantie-gnu-toolchain/opt/riscv/bin/riscv64-unknown-elf-gcc -march=rv64gc_zfh_xtheadmatrix -g layernorm_v2.c -o layernorm_v2.elf -O2 -lm -static
# 	/cluster/home/guoym/xuantie-gnu-toolchain/opt/riscv/bin/riscv64-unknown-elf-gcc -march=rv64gcv_zfh_xtheadmatrix -g ffn.c -o ffn.elf -O2 -lm -static
# 	/cluster/home/guoym/xuantie-gnu-toolchain/opt/riscv/bin/riscv64-unknown-elf-gcc -march=rv64gc_zfh_xtheadmatrix -g igelu.c -o igelu.elf -O2 -lm -static
exe:
# 	/cluster/home/guoym/xuantie-gnu-toolchain/opt/riscv/bin/riscv64-unknown-elf-gcc -march=rv64gc_zfh_xtheadmatrix -g test.c -o test -O2 -lm -static
# 	/cluster/home/guoym/xuantie-gnu-toolchain/opt/riscv/bin/riscv64-unknown-elf-gcc -march=rv64gc_zfh_xtheadmatrix -g test1.c -o test1 -O2 -lm -static
# 	/cluster/home/guoym/xuantie-gnu-toolchain/opt/riscv/bin/riscv64-unknown-elf-gcc -march=rv64gc_zfh_xtheadmatrix -mabi=lp64d -g ffn.c -o ffn -O2 -lm -static
# 	/cluster/home/guoym/xuantie-gnu-toolchain/opt/riscv/bin/riscv64-unknown-elf-gcc -march=rv64gc_zfh_xtheadmatrix -g test2.c -o test2 -O2 -lm -static
# 	/cluster/home/guoym/xuantie-gnu-toolchain/opt/riscv/bin/riscv64-unknown-elf-gcc -march=rv64gc_zfh_xtheadmatrix -g test3.c -o test3 -O2 -lm -static
# 	/cluster/home/guoym/xuantie-gnu-toolchain/opt/riscv/bin/riscv64-unknown-elf-gcc -march=rv64gc_zfh_xtheadmatrix -g instruction_test.c -o instruction_test -O2 -lm -static
# 	/cluster/home/guoym/xuantie-gnu-toolchain/opt/riscv/bin/riscv64-unknown-elf-gcc -march=rv64gc_zfh_xtheadmatrix -g matmul_v2_3.c -o matmul_v2_3 -O3 -lm -static
# 	/cluster/home/guoym/xuantie-gnu-toolchain/opt/riscv/bin/riscv64-unknown-elf-gcc -march=rv64gc_zfh_xtheadmatrix -g matmul_u.c -o matmul_u -O2 -lm -static
# 	/cluster/home/guoym/xuantie-gnu-toolchain/opt/riscv/bin/riscv64-unknown-elf-gcc -march=rv64gc_zfh_xtheadmatrix -g matmul_redc.c -o matmul_redc -O2 -lm -static
# 	/cluster/home/guoym/xuantie-gnu-toolchain/opt/riscv/bin/riscv64-unknown-elf-gcc -march=rv64gc_zfh_xtheadmatrix -g attention_v2.c -o attention_v2 -O2 -lm -static
	/cluster/home/guoym/xuantie-gnu-toolchain/opt/riscv/bin/riscv64-unknown-elf-gcc -march=rv64gc_zfh_xtheadmatrix -g $(TARGET).c -o $(TARGET) -O2 -lm -static
# 	/cluster/home/guoym/xuantie-gnu-toolchain/opt/riscv/bin/riscv64-unknown-elf-gcc -march=rv64gc_zfh_xtheadmatrix -g mat_lut.c -o mat_lut -O2 -lm -static
# 	/cluster/home/guoym/xuantie-gnu-toolchain/opt/riscv/bin/riscv64-unknown-elf-gcc -march=rv64gc_zfh_xtheadmatrix -g loadt_test.c -o loadt_test -O2 -lm -static
# 	/cluster/home/guoym/xuantie-gnu-toolchain/opt/riscv/bin/riscv64-unknown-elf-gcc -march=rv64gc_zfh_xtheadmatrix -g matmul_v2.c -o matmul_v2 -O2 -lm -static
# 	/cluster/home/guoym/xuantie-gnu-toolchain/opt/riscv/bin/riscv64-unknown-elf-gcc -march=rv64gc_zfh_xtheadmatrix -g softmax_v2_1.c -o softmax_v2_1 -O2 -lm -static
# 	/cluster/home/guoym/xuantie-gnu-toolchain/opt/riscv/bin/riscv64-unknown-elf-gcc -march=rv64gc_zfh_xtheadmatrix -g attention.c -o attention -O2 -lm -static
# 	/cluster/home/guoym/xuantie-gnu-toolchain/opt/riscv/bin/riscv64-unknown-elf-gcc -march=rv64gc_zfh_xtheadmatrix -g layernorm_v2.c -o layernorm_v2 -O2 -lm -static
# 	/cluster/home/guoym/xuantie-gnu-toolchain/opt/riscv/bin/riscv64-unknown-elf-gcc -march=rv64gc_zfh_xtheadmatrix -g ffn.c -o ffn -O2 -lm -static
# 	/cluster/home/guoym/xuantie-gnu-toolchain/opt/riscv/bin/riscv64-unknown-elf-gcc -march=rv64gc_zfh_xtheadmatrix -g igelu.c -o igelu -O2 -lm -static


dump:
# 	/cluster/home/guoym/xuantie-gnu-toolchain/opt/riscv/bin/riscv64-unknown-elf-objdump -D test.elf > test.dump
# 	/cluster/home/guoym/xuantie-gnu-toolchain/opt/riscv/bin/riscv64-unknown-elf-objdump -D test1.elf > test1.dump
# 	/cluster/home/guoym/xuantie-gnu-toolchain/opt/riscv/bin/riscv64-unknown-elf-objdump -D test2.elf > test2.dump
# 	/cluster/home/guoym/xuantie-gnu-toolchain/opt/riscv/bin/riscv64-unknown-elf-objdump -D test3.elf > test3.dump
# 	/cluster/home/guoym/xuantie-gnu-toolchain/opt/riscv/bin/riscv64-unknown-elf-objdump -D instruction_test.elf > instruction_test.dump
	/cluster/home/guoym/xuantie-gnu-toolchain/opt/riscv/bin/riscv64-unknown-elf-objdump -D attention_final_v1.elf > attention_final_v1.dump
# 	/cluster/home/guoym/xuantie-gnu-toolchain/opt/riscv/bin/riscv64-unknown-elf-objdump -D matmul_u.elf > matmul_u.dump
# 	/cluster/home/guoym/xuantie-gnu-toolchain/opt/riscv/bin/riscv64-unknown-elf-objdump -D matmul_redc.elf > matmul_redc.dump
# 	/cluster/home/guoym/xuantie-gnu-toolchain/opt/riscv/bin/riscv64-unknown-elf-objdump -D mat_lut.elf > mat_lut.dump
# 	/cluster/home/guoym/xuantie-gnu-toolchain/opt/riscv/bin/riscv64-unknown-elf-objdump -D softmax_v2.elf > softmax_v2.dump
# 	/cluster/home/guoym/xuantie-gnu-toolchain/opt/riscv/bin/riscv64-unknown-elf-objdump -D loadt_test.elf > loadt_test.dump
# 	/cluster/home/guoym/xuantie-gnu-toolchain/opt/riscv/bin/riscv64-unknown-elf-objdump -D layernorm_v2.elf > layernorm_v2.dump
# 	/cluster/home/guoym/xuantie-gnu-toolchain/opt/riscv/bin/riscv64-unknown-elf-objdump -D ffn.elf > ffn.dump
	