import sys

Import('*')

# if not env['CONF']['BUILD_MATRIX_ENGINE']:
#     print("cwqcwqcwqcwqcwq!!!")
#     Return()
# SimObject('matrix_dma.py', sim_objects=['MatrixDmaDevice'])
# SimObject('matrix_spm.py', sim_objects=['MatrixSPM'])
SimObject('matrix_engine_interface.py', sim_objects=['MatrixEngineInterface'])
SimObject('matrix_engine.py', sim_objects=['MatrixEngine'])
# SimObject('Transpose_Unit.py', sim_objects=['TransposeUnit'])

# Source('./spm/matrix_spm.cc')
# Source('./spm/matrix_dma.cc')
Source('matrix_engine_interface.cc')
Source('matrix_engine.cc')
# Source('./transpose_unit/Transpose_Unit.cc')

DebugFlag('MatrixEngineInterface')
# DebugFlag('Transpose_Unit')
DebugFlag('MatrixEngine')
# DebugFlag('MatrixSPM')
# DebugFlag('SPMBank')
# DebugFlag('MatrixDMA')
# DebugFlag('MatrixDMAPort')